sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - dev # build master branch only
install:
  - npm install
script:
  - hexo generate # generate static files
after_script:
  - cd ./public
  - git init
  - git config user.name $USERNAME
  - git config user.email $USEREMAIL
  - git add .
  - git commit -m "Update Doc"
  - git push -f "https://${GH_TOKEN}@${GH_REF}" master:master

env:
  global:
    - GH_REF: github.com/yqzzxlj/yqzzxlj.github.io.git